name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Update APT cache
        run: |
          sudo apt-get update

      - name: Get build dependencies
        run: |
          echo "Generating Debian source for usage on Ubuntu/focal / ubuntu-20.04"
          cd pkg/deb/
          ./generator.sh
          ./backports/focal
          rm -rf debian
          mv focal debian
          echo "Installing Debian packages"
          sudo apt-get build-dep -q -y -Ppkg.ngcp-rtpengine.nobcg729 .

      - name: Run unit tests with sanitizers enabled
        run: |
          make asan-check
